### ISSUE TITLE
[Estética] Modelo do case 3D que vai conter o circuito

### ISSUE THREAD

**Issue by MelvinGust** [MelvinGust/Cadeira-3E#12]
Precisamos achar / projetar o modelo do case que vai conter o circuito dentro dele, para logo depois realizar a impressão.

Será encaminhado como comentário o módelo escolhido e suas dimensões.

**Comment by LucianoCFF** [comment]
![image](https://github.com/3E-Unicamp/Projeto-Cadeira/assets/146268031/af3a53ab-5231-4fea-8aa6-e1466f1d9b34)
![image](https://github.com/3E-Unicamp/Projeto-Cadeira/assets/146268031/d16f2e06-dbeb-4a37-808b-dfb4785ec583)
![image](https://github.com/3E-Unicamp/Projeto-Cadeira/assets/146268031/bca63d8a-6d3d-4702-b419-5c34f56c6d24)
![image](https://github.com/3E-Unicamp/Projeto-Cadeira/assets/146268031/ef01a5d3-4384-4c22-a6bd-d49b0fc3d550)
![image](https://github.com/3E-Unicamp/Projeto-Cadeira/assets/146268031/b4fedfd5-109b-4bcc-96a8-9e2eb453b846)

**Comment by LucianoCFF** [comment]
Dimensões
altura:53mm
Largura:60mm
Comprimento:120mm
Furos para botões : 8mm
Furo para parafusar: 4mm por 30mm

**Comment by LucianoCFF** [comment]
altura medida com tampa
