### ISSUE TITLE
[Documentação] Descrever o funcionamento do circuito na documentação

### ISSUE THREAD

**Issue by MelvinGust** [MelvinGust/Cadeira-3E#8]
Com esta atividade espera-se seja realizada a elaboração da documentação descrevendo o funcionamento do circuito eletrônico desenvolvido.

**Comment by LucianoCFF** [comment]
O circuito funciona como um divisor de tensão, são 4 resistores em série, dois possuindo um valor de 500ohm, e dois de 10Kohm, o primeiro resistor do circuito possui valor de 500ohm seguidos por dois resistores de 10Kohm e por último um resistor de 500ohm, todos os resistores são conectados em série, a tensão medida pelo microcontrolador é a tensão em cima do terceiro resistor do circuito, ou segundo resistor de 10Kohm, para alterar a tensão medida daremos curtos nos resistores de 10K ohm, podendo assim variar para próxima da tensão máxima de alimentação, para o estado neutro no qual é a metade da tensão de alimentação, e estado com tensão próximo de zero.
Os resistores de 500Ohm servem como uma proteção para evitar o curto total do circuito.
