### ISSUE TITLE
[Eletrônica] Montagem da PCB do controlador

### ISSUE THREAD

**Issue by MelvinGust** [MelvinGust/Cadeira-3E#9]
Nesta etapa seria criado um esquemático para impressão de PCB da Cadeira de Rodas. A ideia é desenharmos o controle correspondente em EasyEDA, exportar o arquivo Gerber e encaminhar para produção.

Como resposta, precisamos ter como comentário uma imagem do circuito junto com seu arquivo Gerber.

**Comment by LucianoCFF** [comment]
![image](https://github.com/3E-Unicamp/Projeto-Cadeira/assets/146268031/4348e3c5-593e-4e35-9b52-51760c86c10c)
Esta imagem representa o circuito desenvolvido da cadeira, a entradas J11 e J5 são os pino que estarão conectados na placa do controle, a entra 1 e 3 é a alimentação, e a entrada 2 a leitura de tesão do microcontrolador, as entradas U1, U2 e U3 são os pino dos botões que irão para a cabeceira da cadeira as entradas J1 e J2, são extensões para se conectar o botão do circuito do controle na placa desenvolvida para depois serem estendidos para botões externos que estarão na cadeira, os componentes R1, R2, R6 e R5 são resistores de 500ohm, e os componentes R4, R3, R7 e R8, são resistores de 10Kohm.

**Comment by LucianoCFF** [comment]
![image](https://github.com/3E-Unicamp/Projeto-Cadeira/assets/146268031/b479dbfe-966c-4fff-b126-7eb900968f1c)
A placa possui dimensões de 30mm de largura por 40mm de altura.

**Comment by LucianoCFF** [comment]
[Gerber_PCB_3Cadeira_2023-11-09 (1).zip](https://github.com/3E-Unicamp/Projeto-Cadeira/files/13326135/Gerber_PCB_3Cadeira_2023-11-09.1.zip)
Arquivo Gerber do circuito desenvolvido.
